# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea7077586ea256c35e7beefab539756cdbdd3310b864a2e2785f1416571c82eece5c0700ba4b2cb3a8262848fb2e7cc5b8dd6f32b43b65f0406bd751f8b3c097

test:
  secret_key_base: 9f5fec4430a1309264bcd082d6946693e24f0e9863ebb0446fb4f699f34d250edd9760a84b8c86861c2c6f850fadbebdb6186bf76e13f31518dc5347e834478a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
